/*************************************************************************
 * Clus - Software for Predictive Clustering *
 * Copyright (C) 2007 *
 * Katholieke Universiteit Leuven, Leuven, Belgium *
 * Jozef Stefan Institute, Ljubljana, Slovenia *
 * *
 * This program is free software: you can redistribute it and/or modify *
 * it under the terms of the GNU General Public License as published by *
 * the Free Software Foundation, either version 3 of the License, or *
 * (at your option) any later version. *
 * *
 * This program is distributed in the hope that it will be useful, *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the *
 * GNU General Public License for more details. *
 * *
 * You should have received a copy of the GNU General Public License *
 * along with this program. If not, see <http://www.gnu.org/licenses/>. *
 * *
 * Contact information: <http://www.cs.kuleuven.be/~dtai/clus/>. *
 *************************************************************************/

/*
 * Created on May 1, 2005
 */

package si.ijs.kt.clus.algo.rules;

import java.io.IOException;

import si.ijs.kt.clus.Clus;
import si.ijs.kt.clus.algo.ClusInductionAlgorithm;
import si.ijs.kt.clus.algo.ClusInductionAlgorithmType;
import si.ijs.kt.clus.algo.rules.probabilistic.ClusRuleProbabilisticRuleSetInduce;
import si.ijs.kt.clus.algo.tdidt.ClusDecisionTree;
import si.ijs.kt.clus.data.ClusSchema;
import si.ijs.kt.clus.data.type.ClusAttrType.AttributeUseType;
import si.ijs.kt.clus.data.type.primitive.NumericAttrType;
import si.ijs.kt.clus.main.ClusRun;
import si.ijs.kt.clus.main.settings.Settings;
import si.ijs.kt.clus.main.settings.section.SettingsRules.CoveringMethod;
import si.ijs.kt.clus.model.ClusModel;
import si.ijs.kt.clus.model.ClusModelInfo;
import si.ijs.kt.clus.util.exception.ClusException;
import si.ijs.kt.clus.util.jeans.util.cmdline.CMDLineArgs;


public class ClusRuleClassifier extends ClusInductionAlgorithmType {

    public ClusRuleClassifier(Clus clus) {
        super(clus);
    }


    @Override
    public ClusInductionAlgorithm createInduce(ClusSchema schema, Settings sett, CMDLineArgs cargs) throws ClusException, IOException {

        // Compute the normalization information here if needed. We can here use the whole data set
        // instead of only the training set part. This is how trees are using it also.
        // Both default rule creation and rule omitting need the information also
        if (sett.getRules().isRulePredictionOptimized()) {
            NumericAttrType[] descrNumTypes = schema.getNumericAttrUse(AttributeUseType.Descriptive);
            NumericAttrType[] tarNumTypes = schema.getNumericAttrUse(AttributeUseType.Target);
            RuleNormalization.initialize(Clus.calcStdDevsForTheSet(getClus().getData(), descrNumTypes), Clus.calcStdDevsForTheSet(getClus().getData(), tarNumTypes));
        }

        ClusInductionAlgorithm induce;
        if (sett.getRules().getCoveringMethod().equals(CoveringMethod.RulesFromTree)) {
            induce = new ClusRuleFromTreeInduce(schema, sett, getClus());
        }
        else {
            if (sett.getRules().getCoveringMethod().equals(CoveringMethod.SampledRuleSet)) {
                induce = new ClusRuleProbabilisticRuleSetInduce(schema, sett, getClus());
            }
            else if (sett.getILevelC().isSectionILevelCEnabled()) {
                induce = new ClusRuleConstraintInduce(schema, sett);
            }
            else {
                induce = new ClusRuleInduce(schema, sett);
            }
            induce.getStatManager().setRuleInduceOnly(true); // Tells that the rule is the way to go
        }
        induce.getStatManager().initRuleSettings();
        return induce;
    }


    @Override
    public void printInfo() {
        if (getSettings().getRules().getCoveringMethod().equals(CoveringMethod.SampledRuleSet)) {
            System.out.println("RuleSystem based on sampling from initial set of rules generated by: " + getSettings().getRules().getInitialRuleGeneratingMethod().toString());
        }
        else if (getSettings().getRules().isRandomRules()) {
            System.out.println("RuleSystem generating random rules");
        }
        else {
            System.out.println("RuleSystem based on CN2");
            System.out.println("Heuristic: " + getStatManager().getHeuristicName());
        }
    }


    @Override
    public void pruneAll(ClusRun cr) throws ClusException, IOException {
    }


    @Override
    public ClusModel pruneSingle(ClusModel model, ClusRun cr) throws ClusException, IOException {
        return model;
    }


    @Override
    public void postProcess(ClusRun cr) throws ClusException, IOException, InterruptedException {
        // For RulesFromTree the default is already an ensemble.
        if (!getSettings().getRules().getCoveringMethod().equals(CoveringMethod.RulesFromTree) && !getSettings().getRules().getCoveringMethod().equals(CoveringMethod.SampledRuleSet)) {
            ClusModelInfo def_model = cr.addModelInfo(ClusModel.DEFAULT);
            def_model.setModel(ClusDecisionTree.induceDefault(cr));
        }
    }
}
